### ISSUE TITLE
mlp issue

### ISSUE THREAD

**Issue by ghost** [kglore/llnet_color#1]
Traceback (most recent call last):
  File "llnet_color.py", line 599, in <module>
    sda = cPickle.load(f)
  File "/usr/local/lib/python2.7/dist-packages/mlp/__init__.py", line 1, in <module>
    from .model import *
  File "/usr/local/lib/python2.7/dist-packages/mlp/model.py", line 4, in <module>
    from keras.regularizers import l1l2
ImportError: cannot import name l1l2

**Comment by Ir1d** [comment]
https://github.com/alvarouc/mlp/issues/5#issuecomment-353841721

**Comment by kglore** [comment]
Hi @ak9250, sorry for the delays as I currently have my own time to look into the issue. I have committed an update to load only the model parameters instead of loading the pickled object, which was unstable due to version incompatibility. Please consult the readme page again for the current commit for some instructions to run the model. Cheers!
