### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HiddenLayer'

### ISSUE THREAD

**Issue by Ir1d** [kglore/llnet_color#2]
```
Traceback (most recent call last):
  File "llnet_color.py", line 599, in <module>
    sda = cPickle.load(f)
AttributeError: 'module' object has no attribute 'HiddenLayer'
```

Hi I tried with both models from Dropbox and Bitbucket. They resulted the same.
Any hint on solving this? Thx in advance.

**Comment by kglore** [comment]
Hi lr1d. Thank you for your interest. Unfortunately I am trying to debug it myself without success. Long time ago I stored the weights as a pickled object and most of the internal theano backend functions had changed. I would try to find out more about it and come up with a better documentation of the packages used if I found a solution.

**Comment by Ir1d** [comment]
@kglore Hi, thank you for your time and coming back to this. Hope you find a solution eventually :)

**Comment by kglore** [comment]
Hello @Ir1d, thanks for giving me a long-needed poke to fix some of the issues! I have updated the codebase and the model, but the results may still be impacted due to numerical incompatibilities. Please go through the readme page again and hopefully the new setup instructions will work for you. Cheers!

**Comment by Ir1d** [comment]
@kglore Hi, I'm having the  `insecure string pickle` problem, can you share the sha256sum for the model  file so that I could check if I downloaded without corruption?

```
7c0be1f787b3a4bea8e8579d8c606ca3213e5b9b7d807df953e64ddb99caefe1  ./model/003_model.wgt
```

```
python llnet_color.py test ./img/1.png ./model/003_model.wgt
```

```
... Runnning algorithm!
Traceback (most recent call last):
  File "llnet_color.py", line 615, in <module>
    sda = cPickle.load(f)
ValueError: insecure string pickle
```

**Comment by Ir1d** [comment]
Okay I redownloaded this model and came to a new error msg

```
  File "llnet_color.py", line 617, in <module>
    denoise_overlapped_strides();
TypeError: denoise_overlapped_strides() takes at least 1 argument (0 given)

```

I changed the line 617 and resulted this:

```
Traceback (most recent call last):
  File "llnet_color.py", line 617, in <module>
    denoise_overlapped_strides(te_noisy_image);
  File "llnet_color.py", line 562, in denoise_overlapped_strides
    sda.logLayer.y_pred,givens={
AttributeError: 'list' object has no attribute 'logLayer
```

**Comment by kglore** [comment]
Updated llnet_color.py. There was a problem with the cmd line interface. Did it work when you run the GUI interface? i.e. "python llnet_color.py" without all the arguments?

**Comment by Ir1d** [comment]
Hi, I'm running this on a server without GUI interface. I installed easygui btw.
I created a new conda environment as your README, than I had to upgrade numpy to latest version to avoid `ImportError: numpy.core.multiarray failed to import` (from 1.15.0 to numpy-1.16.4-cp27-cp27mu-manylinux1_x86_64.whl)
than it told me this:

```
Traceback (most recent call last):
  File "llnet_color.py", line 632, in <module>
    denoise_overlapped_strides(te_noisy_image);
  File "llnet_color.py", line 563, in denoise_overlapped_strides
    sda.x: test_set_x},on_unused_input='warn')#,profile=True)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/cc.py", line 1587, in cthunk_factory
    key = self.cmodule_key()
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/cc.py", line 1285, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/ir1d/anaconda3/envs/llnet/lib/python2.7/site-packages/theano/gof/cc.py", line 1364, in cmodule_key_
    numpy.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', InplaceDimShuffle{x,0}(b), '\n', "'module' object has no attribute '_get_ndarray_c_version'")
```

I also tried `pip install numpy==1.12.1` but `numpy.core.multiarray failed to import`

```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
```

Any hint on solving this?

**Comment by kglore** [comment]
@Ir1d : I used to encounter this recently when trying to re-test this repository, and I solved it by setting up a new conda environment again with a lower version of numpy (contrary to what you attempted) and eventually ended up with the list of packages listed in req.txt that worked. I'm afraid to say that I do not exactly know how to solve this from your current state. :(

Not sure if Theano isn't playing well with numpy. You might be able to find some more information exploring this thread: https://github.com/pymc-devs/pymc3/issues/3340. There, the solution seems to be updating Theano, but I don't know if it will work with this code now.

**Comment by AnuSMU** [comment]
I am having a similar issue. I am running it on windows platform using the GUI mode. While I import the existing model as uploaded on Dropbox by you, I get the following error. Any workaround? 

AttributeError: 'LogisticRegression' object has no attribute 'image_norm'

Traceback (most recent call last):
  File "--\llnet_color-master\llnet_color.py", line 664, in <module>
    n_outs=prod
  File "--\llnet_color-master\llnet_color.py", line 103, in __init__
    self.finetune_cost = self.logLayer.image_norm(self.y, obj=self)
AttributeError: 'LogisticRegression' object has no attribute 'image_norm'
